### ISSUE TITLE
Auto authorize request does not work for ssh logins

### ISSUE THREAD

**Issue by Silvest89** [chiff-app/chiff-ios#20]
I haven't tested website logins since I only use chiff for SSH. The auto-authorize toggle does not work for ssh logins

**Comment by bas-d** [comment]
I'm not being able to reproduce this, what is the behaviour you expect and the behaviour that you see?

Perhaps the name of the setting is not very clear. Apologies if you already know this, but just in case: when it is disabled, you will get an alert where you need to explicitly approve or deny the request. When approved, you need to authorise with FaceID. 
If the setting is enabled, you don't see the request, but still need to authorise with FaceID.
The secrets are stored in Keychain and directly tied to FaceID, so it's not possible to sign an ssh request (or retrieve other secrets) without authorising with FaceID, unless we use a less secure method of storing the secrets in the Keychain.

**Comment by bas-d** [comment]
Can't reproduce
