### ISSUE TITLE
FF app, webauthn

### ISSUE THREAD

**Issue by systemcrash** [chiff-app/chiff-ios#30]
https://webauthn.io/

asdf@webauthn.io
Register

"webauthn wants to register an account..."

nothing happens in addon or app.

**Comment by bas-d** [comment]
Hmm, weird. Can you confirm that you have extension version 3.3.1 installed in Firefox and that the extension is paired with the phone?

**Comment by systemcrash** [comment]
FF shows 3.2.1 - followed install from website. 

Can you please add version number under "settings" ("about"?) in the addon?  Or somewhere prominent. 

iOS 3.13.0

**Comment by systemcrash** [comment]
"Page not found":

https://www.chiff.app/assets/downloads/chiff-firefox-3.3.1.xpi

**Comment by bas-d** [comment]
Ah you're right, didn't update the website yet, only the mozilla add-on store. Should be on the website in a few minutes, you can also download it here: https://addons.mozilla.org/en-GB/firefox/addon/chiff-app/.

**Comment by systemcrash** [comment]
OK - got it installed (via mozilla addons) and linked. 

It worked. 

Please remove the "do you want to log in to X with chiff" question from the auth flow from the addon. Just have the (iOS) app question the user. Otherwise I can log in with a username and password faster...

From the dialogue it is not unambiguous whether the "yes, always, not now, don't ask again" are global or only for the site we interact with.

**Comment by systemcrash** [comment]
A register sequence seems to produce a strange result when it already exists in the iOS app. The purple "add account" screen just hangs there after my facial recognition. ( Let's pretend I am really dumb and do not notice I already made an account here )

**Comment by systemcrash** [comment]
How does one escape from the "do not ask me again" once it is set?

**Comment by systemcrash** [comment]
> A register sequence seems to produce a strange result when it already exists in the iOS app. The purple "add account" screen just hangs there after my facial recognition. ( Let's pretend I am really dumb and do not notice I already made an account here )

Similar result if I press "Deny" during auth sequence. Some result, I think, should propagate back to the browser.

**Comment by bas-d** [comment]
Glad to hear it. 
In order:

1. The reason the question is asked, is that if you answer no, it wil fall back to native WebAuthn methods. Otherwise it would block that, which may lead to unwanted situations where Chiff prevents you from using another WebAuthn authenticator. 

2. Interactions with notifications are always in the context of the website.

3. That shouldn't happen, created a separate issue for that: https://github.com/chiff-app/chiff-ios/issues/31

4. There is no interface to reset that (yet). Deleting and reinstalling the extension and pairing with the phone would fix it though.

**Comment by systemcrash** [comment]
Otherwise, nice start :)

**Comment by systemcrash** [comment]
4. Re-pairing seems to do the job OK
