### ISSUE TITLE
Allow adding OTP through pairing QR scanner

### ISSUE THREAD

**Issue by systemcrash** [chiff-app/chiff-ios#32]
Should one be able to add chiff to github as a security key or auth app?

Krypton could behave as a security key here. 
Also possible for it to behave as the 2FA auth app (to produce OTCs) 

If not, is this functionality desirable in this suite? ( This is my vote if it is feasible )

**Comment by systemcrash** [comment]
Ok, the 2FA part is a bit hidden ( I assumed that adding the QR code to chiff app would trigger an add sequence ) - I found the click sequence to add the 2FA QR.

**Comment by systemcrash** [comment]
So, perhaps having just one QR code scanner to handle this would be an improvement for the iOS app. To link the browser extension and app, and to add 2FA for sites. 

2FA QR codes, in my understanding generally have this format for e.g. github:

otpauth://totp/GitHub:username?secret=BLAHXYZBLAHXYZ&issuer=GitHub

Pairing URLs go like:

chiff.app/pair?p=zxcvbnmnbvcxz&q=?zxcv5678zxcv&v=1&t=0&b=firefox&o=mac%20os

So it should be evident from the QR code content what the action is. Or?

**Comment by bas-d** [comment]
Yes, I can add that. Probably need an interface to pick an account in case the account cannot be matched (not sure that the host and username values are always set correct in de otp url) or to create a new one if it doesn't exist yet.
