### ISSUE TITLE
A fix needed for https://www.passkeys.io/

### ISSUE THREAD

**Issue by systemcrash** [chiff-app/chiff-ios#33]
I can 'sign up' fine. 

When it's time to 'sign in' with a 'passkey', the iOS app portion completes (login successful), but the FF browser ext hangs there at `confirm login request on your phone now...`. Same whether sign in with email or passkey. 

Identical behaviour to symptoms described in #31

**Comment by bas-d** [comment]
I haven't been able to reproduce. Could you make sure error logging is turned on in the app and let me know when it occurs again? Maybe the logs will provide a hint..

**Comment by systemcrash** [comment]
I never switched error logging off - and by virtue of an error or crash not having occurred for these interactions, I'm not sure what to try next. The app seems to have made it further now. but the extension still hangs there. 

![passkeys](https://github.com/chiff-app/chiff-ios/assets/647633/26142fef-e7db-4f29-b077-2dfe548ca411)

**Comment by bas-d** [comment]
Will be fixed in extension v3.4.0.
